### ISSUE TITLE
「偽らざる明日へ＆ニフル」の新スキル実装

### ISSUE THREAD

**Issue by puarts** [puarts/FehBattleSimulator#124]
![20210719_0419](https://user-images.githubusercontent.com/71858166/126072923-411dd2d0-a61f-477b-802e-9d043e7888cb.jpg)

全スキル一覧
https://puarts.com/?pid=1329

スキル検索
https://puarts.com/?pid=1677

**Comment by puarts** [comment]
絶氷のブレスと虎神・寅は状態異常を付与できる場合のみ、afflictor扱いになって攻撃優先度上がるらしい

**Comment by puarts** [comment]
どうやらギンヌンガガプの加算ダメージは祈りで軽減した分も加算されるらしいけど、敵がベレトで、覇天でダメ軽減無効化してきた場合は祈りは加味されなくなるらしい。
なんかバグっぽい挙動..

**Comment by yakitori-776** [comment]
現在ギンヌンガガプ実装のために色々実験、調査中ですが
「奥義以外のダメージ軽減無効」の相手だと祈りは加味されないが兜や盾は加味されるという意味でしょうか？
