### ISSUE TITLE
竜たちの収穫祭で登場した超英雄の新スキル実装

### ISSUE THREAD

**Issue by puarts** [puarts/FehBattleSimulator#16]
速さの大応援+、蒼紅のブレス、正面隊形・自己3、黒夜のブレス+、攻撃魔防の密集3、変身のカード、竜の逆鱗3、邪竜の大鱗、暁闇のブレスを実装します。

**Comment by yakitori-776** [comment]
変身のカードがhttps://puarts.com/?pid=1469に見つかりませんでした。
チキの蒼紅のブレスの効果のテキストが強化ではなく弱化になっていました(https://puarts.com/?fehskill=1498)。
