### ISSUE TITLE
新スキル【再移動（3）】の検証投稿メモ

### ISSUE THREAD

**Issue by yakitori-776** [puarts/FehBattleSimulator#48]
# 移動増減
* グラビティ状態でも3マス移動可能。移動後にグラビティ解除
https://twitter.com/lidick_l/status/1336226536731541504
* 打ち砕くものは影響なし
https://twitter.com/lidick_l/status/1336255645561962496?s=20

# 移動先
* 移動先の検証
https://twitter.com/Jeremiah_FEH/status/1336209178755432453
* 第一印象
https://twitter.com/lidick_l/status/1336240453037948928
* 危険度仮説
https://twitter.com/Jeremiah_FEH/status/1336242151840092161?s=20
* 移動先のおそらく完全版
1. 危険度が低い
2. 移動力の余剰が少ない
3. 移動先のマスが防御床
4. ナナメ移動 > 直線移動
5. 移動手段がワープ
6. 移動距離が長い
7. 上のマス優先
8. 右のマス優先
https://twitter.com/Jeremiah_FEH/status/1336985829357469697?s=20
* 上の修正 (上の6. は移動距離が「短い」の誤り)
1. 危険度が低い
2. 移動力の余剰が少ない
3. 移動先のマスが防御床
4. ナナメ移動 > 直線移動
5. 移動手段がワープ
6. 移動距離が短い
7. 上のマス優先
8. 右のマス優先
https://twitter.com/Jeremiah_FEH/status/1337013584098852865?s=20
* 現在の決定版(4.を対角線条件に修正)
1. 危険度が低い
2. 移動力の余剰が少ない
3. 移動先のマスが防御床
4. ユニットのいるマスの対角線からの距離が近い
5. 移動手段がワープ
6. 移動距離が短い
7. 上のマス優先
8. 右のマス優先
https://twitter.com/Jeremiah_FEH/status/1337374689279135746?s=20
https://twitter.com/Jeremiah_FEH/status/1337381756953980930?s=20

# 疾風迅雷
* 疾風迅雷との検証(迅雷を優先)
https://twitter.com/GameWit53193893/status/1336237431985561601

# 3マスワープ
* 「 3マスを越える距離のワープ移動はできない」の検証
https://twitter.com/ACE5112/status/1336227688588038144
* 3マス以内ならワープ可能(ツイートは伝令ワープの例)
https://twitter.com/3s_kazenama/status/1336215768430604290

# 進軍阻止
* 進軍阻止の影響は受ける
https://twitter.com/lidick_l/status/1336247849781104640

**Comment by puarts** [comment]
最終的にシミュレーターに実装した処理はこちらに記載しておきました。
https://puarts.com/?pid=1450

こちらはクローズしておきますね。
